package dev.trindadedev.snakegame.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF046E00)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF0CCA00)
val onPrimaryContainerLight = Color(0xFF024D00)
val secondaryLight = Color(0xFF136E0A)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF9BF584)
val onSecondaryContainerLight = Color(0xFF19720F)
val tertiaryLight = Color(0xFF00696C)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF00C1C5)
val onTertiaryContainerLight = Color(0xFF00494B)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF2FDE9)
val onBackgroundLight = Color(0xFF151E12)
val surfaceLight = Color(0xFFF2FDE9)
val onSurfaceLight = Color(0xFF151E12)
val surfaceVariantLight = Color(0xFFD7E7CD)
val onSurfaceVariantLight = Color(0xFF3D4B37)
val outlineLight = Color(0xFF6C7B65)
val outlineVariantLight = Color(0xFFBBCBB2)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2A3326)
val inverseOnSurfaceLight = Color(0xFFEAF4E0)
val inversePrimaryLight = Color(0xFF3CE42B)
val surfaceDimLight = Color(0xFFD3DDCA)
val surfaceBrightLight = Color(0xFFF2FDE9)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFECF7E3)
val surfaceContainerLight = Color(0xFFE7F1DE)
val surfaceContainerHighLight = Color(0xFFE1ECD8)
val surfaceContainerHighestLight = Color(0xFFDBE6D2)

val primaryLightMediumContrast = Color(0xFF024000)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF067F00)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF024000)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF277D1B)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF003D3E)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF007A7C)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF2FDE9)
val onBackgroundLightMediumContrast = Color(0xFF151E12)
val surfaceLightMediumContrast = Color(0xFFF2FDE9)
val onSurfaceLightMediumContrast = Color(0xFF0B1308)
val surfaceVariantLightMediumContrast = Color(0xFFD7E7CD)
val onSurfaceVariantLightMediumContrast = Color(0xFF2C3A27)
val outlineLightMediumContrast = Color(0xFF485642)
val outlineVariantLightMediumContrast = Color(0xFF63715C)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2A3326)
val inverseOnSurfaceLightMediumContrast = Color(0xFFEAF4E0)
val inversePrimaryLightMediumContrast = Color(0xFF3CE42B)
val surfaceDimLightMediumContrast = Color(0xFFBFCAB7)
val surfaceBrightLightMediumContrast = Color(0xFFF2FDE9)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFECF7E3)
val surfaceContainerLightMediumContrast = Color(0xFFE1ECD8)
val surfaceContainerHighLightMediumContrast = Color(0xFFD6E0CD)
val surfaceContainerHighestLightMediumContrast = Color(0xFFCAD5C2)

val primaryLightHighContrast = Color(0xFF013500)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF035600)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF013500)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF035600)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF003233)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF005254)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF2FDE9)
val onBackgroundLightHighContrast = Color(0xFF151E12)
val surfaceLightHighContrast = Color(0xFFF2FDE9)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFD7E7CD)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF22301E)
val outlineVariantLightHighContrast = Color(0xFF3F4D39)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2A3326)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFF3CE42B)
val surfaceDimLightHighContrast = Color(0xFFB2BCAA)
val surfaceBrightLightHighContrast = Color(0xFFF2FDE9)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFEAF4E0)
val surfaceContainerLightHighContrast = Color(0xFFDBE6D2)
val surfaceContainerHighLightHighContrast = Color(0xFFCDD8C5)
val surfaceContainerHighestLightHighContrast = Color(0xFFBFCAB7)

val primaryDark = Color(0xFF41E72F)
val onPrimaryDark = Color(0xFF013A00)
val primaryContainerDark = Color(0xFF0CCA00)
val onPrimaryContainerDark = Color(0xFF024D00)
val secondaryDark = Color(0xFF82DB6E)
val onSecondaryDark = Color(0xFF013A00)
val secondaryContainerDark = Color(0xFF046600)
val onSecondaryContainerDark = Color(0xFF89E274)
val tertiaryDark = Color(0xFF44DDE1)
val onTertiaryDark = Color(0xFF003738)
val tertiaryContainerDark = Color(0xFF00C1C5)
val onTertiaryContainerDark = Color(0xFF00494B)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0D160A)
val onBackgroundDark = Color(0xFFDBE6D2)
val surfaceDark = Color(0xFF0D160A)
val onSurfaceDark = Color(0xFFDBE6D2)
val surfaceVariantDark = Color(0xFF3D4B37)
val onSurfaceVariantDark = Color(0xFFBBCBB2)
val outlineDark = Color(0xFF86957E)
val outlineVariantDark = Color(0xFF3D4B37)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDBE6D2)
val inverseOnSurfaceDark = Color(0xFF2A3326)
val inversePrimaryDark = Color(0xFF046E00)
val surfaceDimDark = Color(0xFF0D160A)
val surfaceBrightDark = Color(0xFF323C2E)
val surfaceContainerLowestDark = Color(0xFF081006)
val surfaceContainerLowDark = Color(0xFF151E12)
val surfaceContainerDark = Color(0xFF192216)
val surfaceContainerHighDark = Color(0xFF232C20)
val surfaceContainerHighestDark = Color(0xFF2E372A)

val primaryDarkMediumContrast = Color(0xFF58FB43)
val onPrimaryDarkMediumContrast = Color(0xFF012D00)
val primaryContainerDarkMediumContrast = Color(0xFF0CCA00)
val onPrimaryContainerDarkMediumContrast = Color(0xFF012A00)
val secondaryDarkMediumContrast = Color(0xFF98F281)
val onSecondaryDarkMediumContrast = Color(0xFF012D00)
val secondaryContainerDarkMediumContrast = Color(0xFF4DA33D)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFF5EF1F5)
val onTertiaryDarkMediumContrast = Color(0xFF002B2C)
val tertiaryContainerDarkMediumContrast = Color(0xFF00C1C5)
val onTertiaryContainerDarkMediumContrast = Color(0xFF002829)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF0D160A)
val onBackgroundDarkMediumContrast = Color(0xFFDBE6D2)
val surfaceDarkMediumContrast = Color(0xFF0D160A)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF3D4B37)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD1E1C7)
val outlineDarkMediumContrast = Color(0xFFA7B79E)
val outlineVariantDarkMediumContrast = Color(0xFF85957E)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFDBE6D2)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF232D20)
val inversePrimaryDarkMediumContrast = Color(0xFF035500)
val surfaceDimDarkMediumContrast = Color(0xFF0D160A)
val surfaceBrightDarkMediumContrast = Color(0xFF3E4739)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF030902)
val surfaceContainerLowDarkMediumContrast = Color(0xFF172014)
val surfaceContainerDarkMediumContrast = Color(0xFF212A1E)
val surfaceContainerHighDarkMediumContrast = Color(0xFF2C3528)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF374033)

val primaryDarkHighContrast = Color(0xFFC7FFB4)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF37E026)
val onPrimaryContainerDarkHighContrast = Color(0xFF000F00)
val secondaryDarkHighContrast = Color(0xFFC7FFB4)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFF7FD76A)
val onSecondaryContainerDarkHighContrast = Color(0xFF000F00)
val tertiaryDarkHighContrast = Color(0xFFB1FDFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFF3AD6DA)
val onTertiaryContainerDarkHighContrast = Color(0xFF000E0E)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF0D160A)
val onBackgroundDarkHighContrast = Color(0xFFDBE6D2)
val surfaceDarkHighContrast = Color(0xFF0D160A)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF3D4B37)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFE5F5DA)
val outlineVariantDarkHighContrast = Color(0xFFB7C7AE)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFDBE6D2)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF035500)
val surfaceDimDarkHighContrast = Color(0xFF0D160A)
val surfaceBrightDarkHighContrast = Color(0xFF495344)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF192216)
val surfaceContainerDarkHighContrast = Color(0xFF2A3326)
val surfaceContainerHighDarkHighContrast = Color(0xFF353E30)
val surfaceContainerHighestDarkHighContrast = Color(0xFF404A3B)

private val LightColorScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

private val DarkColorScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)

private val MediumContrastLightColorScheme = lightColorScheme(
    primary = primaryLightMediumContrast,
    onPrimary = onPrimaryLightMediumContrast,
    primaryContainer = primaryContainerLightMediumContrast,
    onPrimaryContainer = onPrimaryContainerLightMediumContrast,
    secondary = secondaryLightMediumContrast,
    onSecondary = onSecondaryLightMediumContrast,
    secondaryContainer = secondaryContainerLightMediumContrast,
    onSecondaryContainer = onSecondaryContainerLightMediumContrast,
    tertiary = tertiaryLightMediumContrast,
    onTertiary = onTertiaryLightMediumContrast,
    tertiaryContainer = tertiaryContainerLightMediumContrast,
    onTertiaryContainer = onTertiaryContainerLightMediumContrast,
    error = errorLightMediumContrast,
    onError = onErrorLightMediumContrast,
    errorContainer = errorContainerLightMediumContrast,
    onErrorContainer = onErrorContainerLightMediumContrast,
    background = backgroundLightMediumContrast,
    onBackground = onBackgroundLightMediumContrast,
    surface = surfaceLightMediumContrast,
    onSurface = onSurfaceLightMediumContrast,
    surfaceVariant = surfaceVariantLightMediumContrast,
    onSurfaceVariant = onSurfaceVariantLightMediumContrast,
    outline = outlineLightMediumContrast,
    outlineVariant = outlineVariantLightMediumContrast,
    scrim = scrimLightMediumContrast,
    inverseSurface = inverseSurfaceLightMediumContrast,
    inverseOnSurface = inverseOnSurfaceLightMediumContrast,
    inversePrimary = inversePrimaryLightMediumContrast,
    surfaceDim = surfaceDimLightMediumContrast,
    surfaceBright = surfaceBrightLightMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
    surfaceContainerLow = surfaceContainerLowLightMediumContrast,
    surfaceContainer = surfaceContainerLightMediumContrast,
    surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
)

private val HighContrastLightColorScheme = lightColorScheme(
    primary = primaryLightHighContrast,
    onPrimary = onPrimaryLightHighContrast,
    primaryContainer = primaryContainerLightHighContrast,
    onPrimaryContainer = onPrimaryContainerLightHighContrast,
    secondary = secondaryLightHighContrast,
    onSecondary = onSecondaryLightHighContrast,
    secondaryContainer = secondaryContainerLightHighContrast,
    onSecondaryContainer = onSecondaryContainerLightHighContrast,
    tertiary = tertiaryLightHighContrast,
    onTertiary = onTertiaryLightHighContrast,
    tertiaryContainer = tertiaryContainerLightHighContrast,
    onTertiaryContainer = onTertiaryContainerLightHighContrast,
    error = errorLightHighContrast,
    onError = onErrorLightHighContrast,
    errorContainer = errorContainerLightHighContrast,
    onErrorContainer = onErrorContainerLightHighContrast,
    background = backgroundLightHighContrast,
    onBackground = onBackgroundLightHighContrast,
    surface = surfaceLightHighContrast,
    onSurface = onSurfaceLightHighContrast,
    surfaceVariant = surfaceVariantLightHighContrast,
    onSurfaceVariant = onSurfaceVariantLightHighContrast,
    outline = outlineLightHighContrast,
    outlineVariant = outlineVariantLightHighContrast,
    scrim = scrimLightHighContrast,
    inverseSurface = inverseSurfaceLightHighContrast,
    inverseOnSurface = inverseOnSurfaceLightHighContrast,
    inversePrimary = inversePrimaryLightHighContrast,
    surfaceDim = surfaceDimLightHighContrast,
    surfaceBright = surfaceBrightLightHighContrast,
    surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
    surfaceContainerLow = surfaceContainerLowLightHighContrast,
    surfaceContainer = surfaceContainerLightHighContrast,
    surfaceContainerHigh = surfaceContainerHighLightHighContrast,
    surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
)

private val MediumContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkMediumContrast,
    onPrimary = onPrimaryDarkMediumContrast,
    primaryContainer = primaryContainerDarkMediumContrast,
    onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
    secondary = secondaryDarkMediumContrast,
    onSecondary = onSecondaryDarkMediumContrast,
    secondaryContainer = secondaryContainerDarkMediumContrast,
    onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
    tertiary = tertiaryDarkMediumContrast,
    onTertiary = onTertiaryDarkMediumContrast,
    tertiaryContainer = tertiaryContainerDarkMediumContrast,
    onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
    error = errorDarkMediumContrast,
    onError = onErrorDarkMediumContrast,
    errorContainer = errorContainerDarkMediumContrast,
    onErrorContainer = onErrorContainerDarkMediumContrast,
    background = backgroundDarkMediumContrast,
    onBackground = onBackgroundDarkMediumContrast,
    surface = surfaceDarkMediumContrast,
    onSurface = onSurfaceDarkMediumContrast,
    surfaceVariant = surfaceVariantDarkMediumContrast,
    onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
    outline = outlineDarkMediumContrast,
    outlineVariant = outlineVariantDarkMediumContrast,
    scrim = scrimDarkMediumContrast,
    inverseSurface = inverseSurfaceDarkMediumContrast,
    inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
    inversePrimary = inversePrimaryDarkMediumContrast,
    surfaceDim = surfaceDimDarkMediumContrast,
    surfaceBright = surfaceBrightDarkMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
    surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
    surfaceContainer = surfaceContainerDarkMediumContrast,
    surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
)

private val HighContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkHighContrast,
    onPrimary = onPrimaryDarkHighContrast,
    primaryContainer = primaryContainerDarkHighContrast,
    onPrimaryContainer = onPrimaryContainerDarkHighContrast,
    secondary = secondaryDarkHighContrast,
    onSecondary = onSecondaryDarkHighContrast,
    secondaryContainer = secondaryContainerDarkHighContrast,
    onSecondaryContainer = onSecondaryContainerDarkHighContrast,
    tertiary = tertiaryDarkHighContrast,
    onTertiary = onTertiaryDarkHighContrast,
    tertiaryContainer = tertiaryContainerDarkHighContrast,
    onTertiaryContainer = onTertiaryContainerDarkHighContrast,
    error = errorDarkHighContrast,
    onError = onErrorDarkHighContrast,
    errorContainer = errorContainerDarkHighContrast,
    onErrorContainer = onErrorContainerDarkHighContrast,
    background = backgroundDarkHighContrast,
    onBackground = onBackgroundDarkHighContrast,
    surface = surfaceDarkHighContrast,
    onSurface = onSurfaceDarkHighContrast,
    surfaceVariant = surfaceVariantDarkHighContrast,
    onSurfaceVariant = onSurfaceVariantDarkHighContrast,
    outline = outlineDarkHighContrast,
    outlineVariant = outlineVariantDarkHighContrast,
    scrim = scrimDarkHighContrast,
    inverseSurface = inverseSurfaceDarkHighContrast,
    inverseOnSurface = inverseOnSurfaceDarkHighContrast,
    inversePrimary = inversePrimaryDarkHighContrast,
    surfaceDim = surfaceDimDarkHighContrast,
    surfaceBright = surfaceBrightDarkHighContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
    surfaceContainerLow = surfaceContainerLowDarkHighContrast,
    surfaceContainer = surfaceContainerDarkHighContrast,
    surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
)