package dev.trindadedev.snakegame.ui.theme

import androidx.compose.material3.lightColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.ui.graphics.Color

internal val primaryLight = Color(0xFF046E00)
internal val onPrimaryLight = Color(0xFFFFFFFF)
internal val primaryContainerLight = Color(0xFF0CCA00)
internal val onPrimaryContainerLight = Color(0xFF024D00)
internal val secondaryLight = Color(0xFF136E0A)
internal val onSecondaryLight = Color(0xFFFFFFFF)
internal val secondaryContainerLight = Color(0xFF9BF584)
internal val onSecondaryContainerLight = Color(0xFF19720F)
internal val tertiaryLight = Color(0xFF00696C)
internal val onTertiaryLight = Color(0xFFFFFFFF)
internal val tertiaryContainerLight = Color(0xFF00C1C5)
internal val onTertiaryContainerLight = Color(0xFF00494B)
internal val errorLight = Color(0xFFBA1A1A)
internal val onErrorLight = Color(0xFFFFFFFF)
internal val errorContainerLight = Color(0xFFFFDAD6)
internal val onErrorContainerLight = Color(0xFF93000A)
internal val backgroundLight = Color(0xFFF2FDE9)
internal val onBackgroundLight = Color(0xFF151E12)
internal val surfaceLight = Color(0xFFF2FDE9)
internal val onSurfaceLight = Color(0xFF151E12)
internal val surfaceVariantLight = Color(0xFFD7E7CD)
internal val onSurfaceVariantLight = Color(0xFF3D4B37)
internal val outlineLight = Color(0xFF6C7B65)
internal val outlineVariantLight = Color(0xFFBBCBB2)
internal val scrimLight = Color(0xFF000000)
internal val inverseSurfaceLight = Color(0xFF2A3326)
internal val inverseOnSurfaceLight = Color(0xFFEAF4E0)
internal val inversePrimaryLight = Color(0xFF3CE42B)
internal val surfaceDimLight = Color(0xFFD3DDCA)
internal val surfaceBrightLight = Color(0xFFF2FDE9)
internal val surfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val surfaceContainerLowLight = Color(0xFFECF7E3)
internal val surfaceContainerLight = Color(0xFFE7F1DE)
internal val surfaceContainerHighLight = Color(0xFFE1ECD8)
internal val surfaceContainerHighestLight = Color(0xFFDBE6D2)

internal val primaryLightMediumContrast = Color(0xFF024000)
internal val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
internal val primaryContainerLightMediumContrast = Color(0xFF067F00)
internal val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val secondaryLightMediumContrast = Color(0xFF024000)
internal val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
internal val secondaryContainerLightMediumContrast = Color(0xFF277D1B)
internal val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val tertiaryLightMediumContrast = Color(0xFF003D3E)
internal val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
internal val tertiaryContainerLightMediumContrast = Color(0xFF007A7C)
internal val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val errorLightMediumContrast = Color(0xFF740006)
internal val onErrorLightMediumContrast = Color(0xFFFFFFFF)
internal val errorContainerLightMediumContrast = Color(0xFFCF2C27)
internal val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val backgroundLightMediumContrast = Color(0xFFF2FDE9)
internal val onBackgroundLightMediumContrast = Color(0xFF151E12)
internal val surfaceLightMediumContrast = Color(0xFFF2FDE9)
internal val onSurfaceLightMediumContrast = Color(0xFF0B1308)
internal val surfaceVariantLightMediumContrast = Color(0xFFD7E7CD)
internal val onSurfaceVariantLightMediumContrast = Color(0xFF2C3A27)
internal val outlineLightMediumContrast = Color(0xFF485642)
internal val outlineVariantLightMediumContrast = Color(0xFF63715C)
internal val scrimLightMediumContrast = Color(0xFF000000)
internal val inverseSurfaceLightMediumContrast = Color(0xFF2A3326)
internal val inverseOnSurfaceLightMediumContrast = Color(0xFFEAF4E0)
internal val inversePrimaryLightMediumContrast = Color(0xFF3CE42B)
internal val surfaceDimLightMediumContrast = Color(0xFFBFCAB7)
internal val surfaceBrightLightMediumContrast = Color(0xFFF2FDE9)
internal val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
internal val surfaceContainerLowLightMediumContrast = Color(0xFFECF7E3)
internal val surfaceContainerLightMediumContrast = Color(0xFFE1ECD8)
internal val surfaceContainerHighLightMediumContrast = Color(0xFFD6E0CD)
internal val surfaceContainerHighestLightMediumContrast = Color(0xFFCAD5C2)

internal val primaryLightHighContrast = Color(0xFF013500)
internal val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
internal val primaryContainerLightHighContrast = Color(0xFF035600)
internal val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val secondaryLightHighContrast = Color(0xFF013500)
internal val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
internal val secondaryContainerLightHighContrast = Color(0xFF035600)
internal val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val tertiaryLightHighContrast = Color(0xFF003233)
internal val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
internal val tertiaryContainerLightHighContrast = Color(0xFF005254)
internal val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val errorLightHighContrast = Color(0xFF600004)
internal val onErrorLightHighContrast = Color(0xFFFFFFFF)
internal val errorContainerLightHighContrast = Color(0xFF98000A)
internal val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
internal val backgroundLightHighContrast = Color(0xFFF2FDE9)
internal val onBackgroundLightHighContrast = Color(0xFF151E12)
internal val surfaceLightHighContrast = Color(0xFFF2FDE9)
internal val onSurfaceLightHighContrast = Color(0xFF000000)
internal val surfaceVariantLightHighContrast = Color(0xFFD7E7CD)
internal val onSurfaceVariantLightHighContrast = Color(0xFF000000)
internal val outlineLightHighContrast = Color(0xFF22301E)
internal val outlineVariantLightHighContrast = Color(0xFF3F4D39)
internal val scrimLightHighContrast = Color(0xFF000000)
internal val inverseSurfaceLightHighContrast = Color(0xFF2A3326)
internal val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
internal val inversePrimaryLightHighContrast = Color(0xFF3CE42B)
internal val surfaceDimLightHighContrast = Color(0xFFB2BCAA)
internal val surfaceBrightLightHighContrast = Color(0xFFF2FDE9)
internal val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
internal val surfaceContainerLowLightHighContrast = Color(0xFFEAF4E0)
internal val surfaceContainerLightHighContrast = Color(0xFFDBE6D2)
internal val surfaceContainerHighLightHighContrast = Color(0xFFCDD8C5)
internal val surfaceContainerHighestLightHighContrast = Color(0xFFBFCAB7)

internal val primaryDark = Color(0xFF41E72F)
internal val onPrimaryDark = Color(0xFF013A00)
internal val primaryContainerDark = Color(0xFF0CCA00)
internal val onPrimaryContainerDark = Color(0xFF024D00)
internal val secondaryDark = Color(0xFF82DB6E)
internal val onSecondaryDark = Color(0xFF013A00)
internal val secondaryContainerDark = Color(0xFF046600)
internal val onSecondaryContainerDark = Color(0xFF89E274)
internal val tertiaryDark = Color(0xFF44DDE1)
internal val onTertiaryDark = Color(0xFF003738)
internal val tertiaryContainerDark = Color(0xFF00C1C5)
internal val onTertiaryContainerDark = Color(0xFF00494B)
internal val errorDark = Color(0xFFFFB4AB)
internal val onErrorDark = Color(0xFF690005)
internal val errorContainerDark = Color(0xFF93000A)
internal val onErrorContainerDark = Color(0xFFFFDAD6)
internal val backgroundDark = Color(0xFF0D160A)
internal val onBackgroundDark = Color(0xFFDBE6D2)
internal val surfaceDark = Color(0xFF0D160A)
internal val onSurfaceDark = Color(0xFFDBE6D2)
internal val surfaceVariantDark = Color(0xFF3D4B37)
internal val onSurfaceVariantDark = Color(0xFFBBCBB2)
internal val outlineDark = Color(0xFF86957E)
internal val outlineVariantDark = Color(0xFF3D4B37)
internal val scrimDark = Color(0xFF000000)
internal val inverseSurfaceDark = Color(0xFFDBE6D2)
internal val inverseOnSurfaceDark = Color(0xFF2A3326)
internal val inversePrimaryDark = Color(0xFF046E00)
internal val surfaceDimDark = Color(0xFF0D160A)
internal val surfaceBrightDark = Color(0xFF323C2E)
internal val surfaceContainerLowestDark = Color(0xFF081006)
internal val surfaceContainerLowDark = Color(0xFF151E12)
internal val surfaceContainerDark = Color(0xFF192216)
internal val surfaceContainerHighDark = Color(0xFF232C20)
internal val surfaceContainerHighestDark = Color(0xFF2E372A)

internal val primaryDarkMediumContrast = Color(0xFF58FB43)
internal val onPrimaryDarkMediumContrast = Color(0xFF012D00)
internal val primaryContainerDarkMediumContrast = Color(0xFF0CCA00)
internal val onPrimaryContainerDarkMediumContrast = Color(0xFF012A00)
internal val secondaryDarkMediumContrast = Color(0xFF98F281)
internal val onSecondaryDarkMediumContrast = Color(0xFF012D00)
internal val secondaryContainerDarkMediumContrast = Color(0xFF4DA33D)
internal val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
internal val tertiaryDarkMediumContrast = Color(0xFF5EF1F5)
internal val onTertiaryDarkMediumContrast = Color(0xFF002B2C)
internal val tertiaryContainerDarkMediumContrast = Color(0xFF00C1C5)
internal val onTertiaryContainerDarkMediumContrast = Color(0xFF002829)
internal val errorDarkMediumContrast = Color(0xFFFFD2CC)
internal val onErrorDarkMediumContrast = Color(0xFF540003)
internal val errorContainerDarkMediumContrast = Color(0xFFFF5449)
internal val onErrorContainerDarkMediumContrast = Color(0xFF000000)
internal val backgroundDarkMediumContrast = Color(0xFF0D160A)
internal val onBackgroundDarkMediumContrast = Color(0xFFDBE6D2)
internal val surfaceDarkMediumContrast = Color(0xFF0D160A)
internal val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
internal val surfaceVariantDarkMediumContrast = Color(0xFF3D4B37)
internal val onSurfaceVariantDarkMediumContrast = Color(0xFFD1E1C7)
internal val outlineDarkMediumContrast = Color(0xFFA7B79E)
internal val outlineVariantDarkMediumContrast = Color(0xFF85957E)
internal val scrimDarkMediumContrast = Color(0xFF000000)
internal val inverseSurfaceDarkMediumContrast = Color(0xFFDBE6D2)
internal val inverseOnSurfaceDarkMediumContrast = Color(0xFF232D20)
internal val inversePrimaryDarkMediumContrast = Color(0xFF035500)
internal val surfaceDimDarkMediumContrast = Color(0xFF0D160A)
internal val surfaceBrightDarkMediumContrast = Color(0xFF3E4739)
internal val surfaceContainerLowestDarkMediumContrast = Color(0xFF030902)
internal val surfaceContainerLowDarkMediumContrast = Color(0xFF172014)
internal val surfaceContainerDarkMediumContrast = Color(0xFF212A1E)
internal val surfaceContainerHighDarkMediumContrast = Color(0xFF2C3528)
internal val surfaceContainerHighestDarkMediumContrast = Color(0xFF374033)

internal val primaryDarkHighContrast = Color(0xFFC7FFB4)
internal val onPrimaryDarkHighContrast = Color(0xFF000000)
internal val primaryContainerDarkHighContrast = Color(0xFF37E026)
internal val onPrimaryContainerDarkHighContrast = Color(0xFF000F00)
internal val secondaryDarkHighContrast = Color(0xFFC7FFB4)
internal val onSecondaryDarkHighContrast = Color(0xFF000000)
internal val secondaryContainerDarkHighContrast = Color(0xFF7FD76A)
internal val onSecondaryContainerDarkHighContrast = Color(0xFF000F00)
internal val tertiaryDarkHighContrast = Color(0xFFB1FDFF)
internal val onTertiaryDarkHighContrast = Color(0xFF000000)
internal val tertiaryContainerDarkHighContrast = Color(0xFF3AD6DA)
internal val onTertiaryContainerDarkHighContrast = Color(0xFF000E0E)
internal val errorDarkHighContrast = Color(0xFFFFECE9)
internal val onErrorDarkHighContrast = Color(0xFF000000)
internal val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
internal val onErrorContainerDarkHighContrast = Color(0xFF220001)
internal val backgroundDarkHighContrast = Color(0xFF0D160A)
internal val onBackgroundDarkHighContrast = Color(0xFFDBE6D2)
internal val surfaceDarkHighContrast = Color(0xFF0D160A)
internal val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
internal val surfaceVariantDarkHighContrast = Color(0xFF3D4B37)
internal val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
internal val outlineDarkHighContrast = Color(0xFFE5F5DA)
internal val outlineVariantDarkHighContrast = Color(0xFFB7C7AE)
internal val scrimDarkHighContrast = Color(0xFF000000)
internal val inverseSurfaceDarkHighContrast = Color(0xFFDBE6D2)
internal val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
internal val inversePrimaryDarkHighContrast = Color(0xFF035500)
internal val surfaceDimDarkHighContrast = Color(0xFF0D160A)
internal val surfaceBrightDarkHighContrast = Color(0xFF495344)
internal val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
internal val surfaceContainerLowDarkHighContrast = Color(0xFF192216)
internal val surfaceContainerDarkHighContrast = Color(0xFF2A3326)
internal val surfaceContainerHighDarkHighContrast = Color(0xFF353E30)
internal val surfaceContainerHighestDarkHighContrast = Color(0xFF404A3B)

internal val LightColorScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

internal val DarkColorScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)

internal val MediumContrastLightColorScheme = lightColorScheme(
    primary = primaryLightMediumContrast,
    onPrimary = onPrimaryLightMediumContrast,
    primaryContainer = primaryContainerLightMediumContrast,
    onPrimaryContainer = onPrimaryContainerLightMediumContrast,
    secondary = secondaryLightMediumContrast,
    onSecondary = onSecondaryLightMediumContrast,
    secondaryContainer = secondaryContainerLightMediumContrast,
    onSecondaryContainer = onSecondaryContainerLightMediumContrast,
    tertiary = tertiaryLightMediumContrast,
    onTertiary = onTertiaryLightMediumContrast,
    tertiaryContainer = tertiaryContainerLightMediumContrast,
    onTertiaryContainer = onTertiaryContainerLightMediumContrast,
    error = errorLightMediumContrast,
    onError = onErrorLightMediumContrast,
    errorContainer = errorContainerLightMediumContrast,
    onErrorContainer = onErrorContainerLightMediumContrast,
    background = backgroundLightMediumContrast,
    onBackground = onBackgroundLightMediumContrast,
    surface = surfaceLightMediumContrast,
    onSurface = onSurfaceLightMediumContrast,
    surfaceVariant = surfaceVariantLightMediumContrast,
    onSurfaceVariant = onSurfaceVariantLightMediumContrast,
    outline = outlineLightMediumContrast,
    outlineVariant = outlineVariantLightMediumContrast,
    scrim = scrimLightMediumContrast,
    inverseSurface = inverseSurfaceLightMediumContrast,
    inverseOnSurface = inverseOnSurfaceLightMediumContrast,
    inversePrimary = inversePrimaryLightMediumContrast,
    surfaceDim = surfaceDimLightMediumContrast,
    surfaceBright = surfaceBrightLightMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
    surfaceContainerLow = surfaceContainerLowLightMediumContrast,
    surfaceContainer = surfaceContainerLightMediumContrast,
    surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
)

internal val HighContrastLightColorScheme = lightColorScheme(
    primary = primaryLightHighContrast,
    onPrimary = onPrimaryLightHighContrast,
    primaryContainer = primaryContainerLightHighContrast,
    onPrimaryContainer = onPrimaryContainerLightHighContrast,
    secondary = secondaryLightHighContrast,
    onSecondary = onSecondaryLightHighContrast,
    secondaryContainer = secondaryContainerLightHighContrast,
    onSecondaryContainer = onSecondaryContainerLightHighContrast,
    tertiary = tertiaryLightHighContrast,
    onTertiary = onTertiaryLightHighContrast,
    tertiaryContainer = tertiaryContainerLightHighContrast,
    onTertiaryContainer = onTertiaryContainerLightHighContrast,
    error = errorLightHighContrast,
    onError = onErrorLightHighContrast,
    errorContainer = errorContainerLightHighContrast,
    onErrorContainer = onErrorContainerLightHighContrast,
    background = backgroundLightHighContrast,
    onBackground = onBackgroundLightHighContrast,
    surface = surfaceLightHighContrast,
    onSurface = onSurfaceLightHighContrast,
    surfaceVariant = surfaceVariantLightHighContrast,
    onSurfaceVariant = onSurfaceVariantLightHighContrast,
    outline = outlineLightHighContrast,
    outlineVariant = outlineVariantLightHighContrast,
    scrim = scrimLightHighContrast,
    inverseSurface = inverseSurfaceLightHighContrast,
    inverseOnSurface = inverseOnSurfaceLightHighContrast,
    inversePrimary = inversePrimaryLightHighContrast,
    surfaceDim = surfaceDimLightHighContrast,
    surfaceBright = surfaceBrightLightHighContrast,
    surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
    surfaceContainerLow = surfaceContainerLowLightHighContrast,
    surfaceContainer = surfaceContainerLightHighContrast,
    surfaceContainerHigh = surfaceContainerHighLightHighContrast,
    surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
)

internal val MediumContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkMediumContrast,
    onPrimary = onPrimaryDarkMediumContrast,
    primaryContainer = primaryContainerDarkMediumContrast,
    onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
    secondary = secondaryDarkMediumContrast,
    onSecondary = onSecondaryDarkMediumContrast,
    secondaryContainer = secondaryContainerDarkMediumContrast,
    onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
    tertiary = tertiaryDarkMediumContrast,
    onTertiary = onTertiaryDarkMediumContrast,
    tertiaryContainer = tertiaryContainerDarkMediumContrast,
    onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
    error = errorDarkMediumContrast,
    onError = onErrorDarkMediumContrast,
    errorContainer = errorContainerDarkMediumContrast,
    onErrorContainer = onErrorContainerDarkMediumContrast,
    background = backgroundDarkMediumContrast,
    onBackground = onBackgroundDarkMediumContrast,
    surface = surfaceDarkMediumContrast,
    onSurface = onSurfaceDarkMediumContrast,
    surfaceVariant = surfaceVariantDarkMediumContrast,
    onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
    outline = outlineDarkMediumContrast,
    outlineVariant = outlineVariantDarkMediumContrast,
    scrim = scrimDarkMediumContrast,
    inverseSurface = inverseSurfaceDarkMediumContrast,
    inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
    inversePrimary = inversePrimaryDarkMediumContrast,
    surfaceDim = surfaceDimDarkMediumContrast,
    surfaceBright = surfaceBrightDarkMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
    surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
    surfaceContainer = surfaceContainerDarkMediumContrast,
    surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
)

internal val HighContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkHighContrast,
    onPrimary = onPrimaryDarkHighContrast,
    primaryContainer = primaryContainerDarkHighContrast,
    onPrimaryContainer = onPrimaryContainerDarkHighContrast,
    secondary = secondaryDarkHighContrast,
    onSecondary = onSecondaryDarkHighContrast,
    secondaryContainer = secondaryContainerDarkHighContrast,
    onSecondaryContainer = onSecondaryContainerDarkHighContrast,
    tertiary = tertiaryDarkHighContrast,
    onTertiary = onTertiaryDarkHighContrast,
    tertiaryContainer = tertiaryContainerDarkHighContrast,
    onTertiaryContainer = onTertiaryContainerDarkHighContrast,
    error = errorDarkHighContrast,
    onError = onErrorDarkHighContrast,
    errorContainer = errorContainerDarkHighContrast,
    onErrorContainer = onErrorContainerDarkHighContrast,
    background = backgroundDarkHighContrast,
    onBackground = onBackgroundDarkHighContrast,
    surface = surfaceDarkHighContrast,
    onSurface = onSurfaceDarkHighContrast,
    surfaceVariant = surfaceVariantDarkHighContrast,
    onSurfaceVariant = onSurfaceVariantDarkHighContrast,
    outline = outlineDarkHighContrast,
    outlineVariant = outlineVariantDarkHighContrast,
    scrim = scrimDarkHighContrast,
    inverseSurface = inverseSurfaceDarkHighContrast,
    inverseOnSurface = inverseOnSurfaceDarkHighContrast,
    inversePrimary = inversePrimaryDarkHighContrast,
    surfaceDim = surfaceDimDarkHighContrast,
    surfaceBright = surfaceBrightDarkHighContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
    surfaceContainerLow = surfaceContainerLowDarkHighContrast,
    surfaceContainer = surfaceContainerDarkHighContrast,
    surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
)