name: Build & Deploy

on:
  push:
    branches: [ "**" ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ "**" ]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  wasm-js:
    name: Build WasmJs Web
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant gradle permission
        run: chmod +x gradlew

      - name: Build WasmJS distribution
        run: ./gradlew :composeApp:wasmJsBrowserDistribution

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: composeApp/build/dist/wasmJs/productionExecutable

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4

  android:
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant gradle permission
        run: chmod +x gradlew

      - name: Build Android APK
        run: ./gradlew :composeApp:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: snake-game-android
          path: composeApp/build/outputs/apk/debug
